// Curated list of common five-letter English words. Doubles as both the pool
// today's answer is drawn from and the set of guesses the game accepts --
// one list keeps this file self-contained with no external dictionary fetch,
// which matters for an offline-first game.
export const ANSWERS = [
  'about', 'above', 'abuse', 'actor', 'acute', 'admit', 'adopt', 'adult', 'after', 'again',
  'agent', 'agree', 'ahead', 'alarm', 'album', 'alert', 'alike', 'alive', 'allow', 'alone',
  'along', 'alter', 'among', 'anger', 'angle', 'angry', 'apart', 'apple', 'apply', 'arena',
  'argue', 'arise', 'array', 'aside', 'asset', 'avoid', 'awake', 'award', 'aware', 'badly',
  'baker', 'bases', 'basic', 'basis', 'beach', 'began', 'begin', 'begun', 'being', 'below',
  'bench', 'birth', 'black', 'blade', 'blame', 'blank', 'blast', 'blend', 'blind', 'block',
  'blood', 'board', 'boost', 'booth', 'bound', 'brain', 'brand', 'brass', 'brave', 'bread',
  'break', 'breed', 'brief', 'bring', 'broad', 'broke', 'brown', 'build', 'built', 'bunch',
  'burst', 'buyer', 'cable', 'carry', 'catch', 'cause', 'chain', 'chair', 'chaos', 'charm',
  'chart', 'chase', 'cheap', 'check', 'chest', 'chief', 'child', 'chose', 'civil', 'claim',
  'class', 'clean', 'clear', 'click', 'cliff', 'climb', 'clock', 'close', 'cloud', 'coach',
  'coast', 'could', 'count', 'court', 'cover', 'craft', 'crash', 'crazy', 'cream', 'crime',
  'cross', 'crowd', 'crown', 'crude', 'curve', 'cycle', 'daily', 'dance', 'dealt', 'death',
  'debut', 'delay', 'depth', 'doing', 'doubt', 'dozen', 'draft', 'drama', 'drank', 'dream',
  'dress', 'drill', 'drink', 'drive', 'drove', 'dying', 'eager', 'early', 'earth', 'eight',
  'elite', 'empty', 'enemy', 'enjoy', 'enter', 'entry', 'equal', 'error', 'event', 'every',
  'exact', 'exist', 'extra', 'faith', 'false', 'fancy', 'fatal', 'fault', 'favor', 'fence',
  'fever', 'fewer', 'field', 'fifth', 'fifty', 'fight', 'final', 'first', 'fixed', 'flame',
  'flash', 'fleet', 'floor', 'fluid', 'focus', 'force', 'forth', 'forty', 'forum', 'found',
  'frame', 'frank', 'fraud', 'fresh', 'front', 'frost', 'fruit', 'fully', 'funny', 'giant',
  'given', 'glass', 'globe', 'glory', 'going', 'grace', 'grade', 'grand', 'grant', 'grass',
  'great', 'green', 'greet', 'grief', 'gross', 'group', 'grown', 'guard', 'guess', 'guest',
  'guide', 'happy', 'harsh', 'heart', 'heavy', 'hence', 'honor', 'horse', 'hotel', 'house',
  'human', 'humor', 'hurry', 'image', 'imply', 'index', 'inner', 'input', 'issue', 'ivory',
  'joint', 'judge', 'juice', 'knife', 'knock', 'known', 'label', 'labor', 'large', 'laser',
  'later', 'laugh', 'layer', 'learn', 'lease', 'least', 'leave', 'legal', 'level', 'light',
  'limit', 'links', 'lives', 'local', 'logic', 'loose', 'lower', 'lucky', 'lunch', 'lying',
  'magic', 'major', 'maker', 'march', 'match', 'maybe', 'mayor', 'meant', 'media', 'metal',
  'might', 'minor', 'minus', 'mixed', 'model', 'moist', 'money', 'month', 'moral', 'motor',
  'mount', 'mouse', 'mouth', 'moved', 'movie', 'music', 'needs', 'never', 'newly', 'night',
  'noise', 'north', 'noted', 'novel', 'nurse', 'occur', 'ocean', 'offer', 'often', 'order',
  'other', 'ought', 'outer', 'owner', 'panel', 'paper', 'party', 'peace', 'phase', 'phone',
  'photo', 'piano', 'piece', 'pilot', 'pitch', 'place', 'plain', 'plane', 'plant', 'plate',
  'point', 'pound', 'power', 'press', 'price', 'pride', 'prime', 'print', 'prior', 'prize',
  'proof', 'proud', 'prove', 'queen', 'quick', 'quiet', 'quite', 'radio', 'raise', 'range',
  'rapid', 'ratio', 'reach', 'ready', 'refer', 'relax', 'reply', 'right', 'rival', 'river',
  'robot', 'roman', 'rough', 'round', 'route', 'royal', 'rural', 'scale', 'scene', 'scope',
  'score', 'sense', 'serve', 'seven', 'shade', 'shake', 'shall', 'shape', 'share', 'sharp',
  'sheet', 'shelf', 'shell', 'shift', 'shine', 'shirt', 'shock', 'shoot', 'short', 'shown',
  'sight', 'since', 'sixth', 'sixty', 'sized', 'skill', 'sleep', 'slide', 'small', 'smart',
  'smile', 'smoke', 'snake', 'solid', 'solve', 'sorry', 'sound', 'south', 'space', 'spare',
  'speak', 'speed', 'spend', 'spent', 'split', 'spoke', 'sport', 'staff', 'stage', 'stake',
  'stand', 'start', 'state', 'steam', 'steel', 'steep', 'stick', 'still', 'stock', 'stone',
  'stood', 'store', 'storm', 'story', 'strip', 'stuck', 'study', 'stuff', 'style', 'sugar',
  'suite', 'super', 'sweet', 'table', 'taken', 'taste', 'teach', 'teeth', 'thank', 'theft',
  'their', 'theme', 'there', 'these', 'thick', 'thing', 'think', 'third', 'those', 'three',
  'threw', 'throw', 'thumb', 'tiger', 'tight', 'timer', 'times', 'tired', 'title', 'today',
  'token', 'topic', 'total', 'touch', 'tough', 'tower', 'track', 'trade', 'trail', 'train',
  'trait', 'treat', 'trend', 'trial', 'tribe', 'trick', 'tried', 'tries', 'truck', 'truly',
  'trunk', 'trust', 'truth', 'twice', 'under', 'union', 'unity', 'until', 'upper', 'upset',
  'urban', 'usage', 'usual', 'valid', 'value', 'video', 'virus', 'visit', 'vital', 'voice',
  'waste', 'watch', 'water', 'wheel', 'where', 'which', 'while', 'white', 'whole', 'whose',
  'woman', 'women', 'world', 'worry', 'worse', 'worst', 'worth', 'would', 'write', 'wrong',
  'wrote', 'yield', 'young', 'youth',
];

export default ANSWERS;
